### ISSUE TITLE
Returning values

### ISSUE THREAD

**Issue by lukaszombiekiller** [Linus045/e2_vgui_core#2]
How would one get the returned values for things like the slide on dslider or the set color with the rgb? There is no mention of how to get these values anywhere and I cannot find help anywhere else.

**Comment by Linus045** [comment]
You need to use `runOnVgui(1)` and then just use the vguiClk() event. E.g.
```
@persist Frame:dframe Slider:dslider

if(first()) {
    runOnVgui(1) #run the E2 when someone uses a derma control (e.g. slider,button,...)
    Frame = dframe(1)
    Frame:center()
    Frame:makePopup()
    Frame:create()
    
    Slider = dslider(2,Frame)
    Slider:setPos(5,50)
    Slider:setValue(50)
    Slider:setMin(0)
    Slider:setMax(100)
    Slider:create()
    
}
if(vguiClk()) { #triggers for each player 
    #vguiClkPanelID() #returns the ID of the derma element. In this case for the slider '2'
    print(Slider:getValue(vguiClkPlayer())) #e.g. 50
    print(vguiClkValues())                  #e.g. array(50)
    printTable(vguiClkValuesTable())        #e.g. table("value" = 50)
}
```
This basically works for every derma element.
Also take a look at the E2Helper because there i added a description for most functions.

I hope this helps you :)

**Comment by Linus045** [comment]
In terms of your color problem: You should be able to use `setColor(V3)` and `V=getColor(E)` for some elements.

Currently there is not such a function for every element because sometimes it doesn't really make sense to color them. If you want to color a specific part of a specific element just ask and I will see if I can add a function for that.
Also remember that changes to an element only get applied if you use `create()` in the initial process and `modify()` on an already created element (e.g. when you use `setColor()` also call `modify()` afterwards to apply the changes).

**Comment by Linus045** [comment]
I'm going to close this issue, if you have any problems related to this feel free to open it again.
